### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by haarts** [impierce/ssi-agent#13]
### Description

Following the instructions in https://github.com/impierce/ssi-agent/tree/dev/agent_api_rest doesn't work. The `openapi.yaml` fails to load. 

### Steps to Reproduce the Bug

1. run `docker run --rm -p 9090:8080 -e SWAGGER_JSON=/tmp/openapi.yaml -v $(pwd):/tmp swaggerapi/swagger-ui` from the `agent_api_rest` directory
2. open localhost:9090

### Expected Behaviour

some API docs

### Actual Behaviour

Error.

### Errors
![image](https://github.com/impierce/ssi-agent/assets/10660/3e2d45ef-7259-4f7f-8591-07aa56fe394b)

**Comment by Norlock** [comment]
We can't reproduce this issue but can you maybe try the following command: 
```shell
docker run --rm -p 9090:8080 -e SWAGGER_JSON=/openapi.yaml -v ./openapi.yaml:/openapi.yaml swaggerapi/swagger-ui
```
And see if you still have this issue?

**Comment by nanderstabel** [comment]
Or else, if the above doesn't work. Could you please try:
```
docker run --rm -p 9090:8080 -e SWAGGER_JSON=/tmp/openapi.yaml -v ${pwd}:/tmp swaggerapi/swagger-ui
```

Assuming you're working on a Windows system?

**Comment by haarts** [comment]
> Assuming you're working on a Windows system?

I'm insulted! Linux here. ;)

![Screenshot from 2024-01-05 19-27-33](https://github.com/impierce/ssi-agent/assets/10660/63b6a42e-517c-483c-8b6e-ef821ed6dc88)

Looks like a perm issue on my side. I'll investigate further. 
None of your suggestions worked BTW. Thanks anyway!

**Comment by haarts** [comment]
Let the scriptures show that having SELinux on the host machine leads to this error. Kinda makes sense even. Solving it is as simple as appending `:z` to the mount point:

```
podman run --rm -p 9090:8080 -e SWAGGER_JSON=/tmp/openapi.yaml -v (pwd):/tmp:z swaggerapi/swagger-ui
``` 

(more info here: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label)
