### ISSUE TITLE
Refactor id property in HTTP API

### ISSUE THREAD

**Issue by daniel-mader** [impierce/ssi-agent#148]
### Description

Scope: **HTTP API**

The identifier of an element in a collection is currently explicitly described as `credential_id` or `offer_id`. While this makes it explicit and distinguishable, it can be safely omitted because the context is carried by the name of the API endpoint already.

This makes it also easier for the consumer of the API by following the convention of having to look for a simple `id` field instead of knowing how the identifier is named.

#### Before
```
[
    {
        "credential_id": "cda45e8d-b4e1-4722-b2ea-59afa3bcd02a",
        ...
```

#### After
```
[
    {
        "id": "cda45e8d-b4e1-4722-b2ea-59afa3bcd02a",
        ...
```

#### Before
```
[
    {
        "offer_id": "001",
        ...
```

#### After
```
[
    {
        "id": "001",
        ...
```

Same applies for all other API endpoints that return a collection of elements identified by some `*_id`, such as `/v0/holder/offers`, `/v0/holder/credentials` and more ...

### Motivation

Cleaner HTTP API, easier to consume and maintain

### Requirements

n/a

### Are you planning to contribute this in a PR?

Yes

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor id property in HTTP API](https://trello.com/c/ouzj1x8P/33-refactor-id-property-in-http-api)
