### ISSUE TITLE
Add health endpoint

### ISSUE THREAD

**Issue by daniel-mader** [impierce/ssi-agent#48]
### Description

Allow basic monitoring of a running UniCore instance by exposing a `/health` endpoint (possibly under the base path `/v1`).
It should return a `200 OK` response with the following body:

```json
{
  "status": "UP"
}
```

### Motivation

Better cloud support, increased monitoring

### Requirements

- [ ] add endpoint `/v1/health`
- [ ] do not return `200 OK` if service is unhealthy

### Are you planning to contribute this in a PR?

Yes

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add health endpoint](https://trello.com/c/H7jJrNCc/11-add-health-endpoint)
