### ISSUE TITLE
Add (pre-)configurable Credential Configurations, deprecate `configurations/credential_configurations` endpoint

### ISSUE THREAD

**Issue by nanderstabel** [impierce/ssi-agent#90]
### Description

As title

### Motivation

In our current solution we have an API to set/update Credential Configurations (introduced here: https://github.com/impierce/ssi-agent/pull/83)

After some feedback it turned out that this approach makes deployments of UniCore and infrastructure more challenging. Therefore we need to deprecate our current API solution and implement a way to 'ingest' Credential Configurations through a config file instead during initialization.

### Resources

n/a

### To-do List

- [x] Deprecate `configurations/credential_configurations` endpoint
- [ ] Add `agent_issuance/issuance-config.yml` file

**Comment by 715209** [comment]
Hi @nanderstabel,

I was wondering why the endpoint was causing deployments of UniCore to be more challenging. How does moving to a config file address these issues?

In situations where credential types might need to be added dynamically, even if these changes are infrequent, wouldn't switching to manual configuration via config files introduce additional complexity? Would a combination of both a config file and the API endpoint work better? By supporting both methods, we could maintain the flexibility to add or update credential configurations dynamically when needed

I'd appreciate any insights you could share on this.
